### ISSUE TITLE
Data8x.2 Checklist

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/data8xhub#33]
- [ ] Get HTTPS certificates for hub.data8x.berkeley.edu
- [ ] Set up HTTPS certificates on inner edge
- [ ] Copy user directories from old NFS servers to new
- [ ] Switch external IP address over
- [ ] Setup Grafana
